[package]
name = "oasis-ethwasi-runtime-common"
version = "0.3.0"
authors = ["Oasis Labs Inc. <info@oasislabs.com>"]

[dependencies]
# Oasis Core.
oasis-core-runtime = { git = "https://github.com/oasisprotocol/oasis-core", tag = "v20.7" }
oasis-core-keymanager-client = { git = "https://github.com/oasisprotocol/oasis-core", tag = "v20.7" }

# Parity.
ethcore = { path = "../../oasis-parity/ethcore" }
ethereum-types = { version = "0.3", default-features = false, features = ["std", "serialize"] }
hashdb = { path = "../../oasis-parity/util/hashdb" }
keccak-hash = { path = "../../oasis-parity/util/hash" }
vm = { path = "../../oasis-parity/ethcore/vm" }

# Others.
elastic-array = "0.10"
failure = "0.1.5"
io-context = "0.2.0"
lazy_static = "1.3.0"
zeroize = "0.10"

[features]
default = []
benchmarking = []
production-genesis = []
test = []
